FROM tensorflow/tensorflow:1.8.0-gpu-py3
ARG FLOWDEC_REPO_URL="https://github.com/hammerlab/flowdec.git"
ARG SIM_DIR=/lab/sim
ARG REPO_DIR=/lab/repos
ARG DATA_DIR=/lab/data
ARG CODEX_REPO_DIR=$REPO_DIR/codex
ARG CVUTILS_REPO_DIR=$REPO_DIR/cvutils

RUN mkdir -p $LAB_DIR $REPO_DIR $DATA_DIR $SIM_DIR

RUN apt-get update && apt-get install -y --no-install-recommends git vim wget

RUN pip --no-cache-dir install \
    jupyterlab \
    scikit-image==0.14.0 \
    matplotlib \
    pandas \
    requests \
    fire \
    dask[distributed] \
    bokeh \
    papermill \
    plotnine \
    seaborn \
    keras \
    fcswrite \
    tifffile

# Install Dash and per their instructions, reference specific verions
# See: https://dash.plot.ly/getting-started
RUN pip install dash==0.21.1  \
    dash-renderer==0.13.0 \
    dash-html-components==0.11.0 \
    dash-core-components==0.23.0 \
    plotly

# OpenCV / Imgaug installation
RUN apt-get install -y libsm6 libxext6 libfontconfig1 libxrender1
RUN pip install opencv-python imgaug

# Install Flowdec
ENV TF_GPU true
RUN cd $REPO_DIR && \
    git clone $FLOWDEC_REPO_URL && \
    cd flowdec/python && \
    pip install .

# Download simulation data for testing
RUN cd $SIM_DIR && \
    wget https://storage.googleapis.com/musc-codex/datasets/simulations/sim-exp-01.zip && \
    unzip -q sim-exp-01.zip

# Add any source directories for development to python search path
RUN mkdir -p $(python -m site --user-site) && \
    echo "$CODEX_REPO_DIR/python/pipeline" > $(python -m site --user-site)/local.pth && \
    echo "$CODEX_REPO_DIR/python/notebooks/src" >> $(python -m site --user-site)/local.pth && \
    echo "$CODEX_REPO_DIR/python/applications" >> $(python -m site --user-site)/local.pth && \
    echo "$CVUTILS_REPO_DIR/python" >> $(python -m site --user-site)/local.pth

WORKDIR "/lab"

ENV CODEX_SIM_DIR $SIM_DIR
ENV CODEX_DATA_DIR $DATA_DIR
ENV CODEX_REPO_DIR $CODEX_REPO_DIR
ENV CVUTILS_REPO_DIR $CVUTILS_REPO_DIR
ENV SHELL /bin/bash

# Eliminate globally these warnings: FutureWarning: Conversion of the second argument of issubdtype from
# `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`
# See here for discussion: https://github.com/h5py/h5py/issues/961
ENV PYTHONWARNINGS "ignore::FutureWarning:h5py"

# Create cli links at runtime instead of container buildtime due to source scripts being
# in repos mounted at runtime
CMD chmod a+x $CODEX_REPO_DIR/python/pipeline/codex/cli/cytokit.py && \
    ln -s $CODEX_REPO_DIR/python/pipeline/codex/cli/cytokit.py /usr/local/bin/cytokit && \
    jupyter lab --allow-root
